/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"

void executer_1(char *host, int x, int y, char *path, char *outputFile)
{
	CLIENT *clnt;
	resultStruct *result_1;
	arguments execute_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, Executer, ADD_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif
	execute_1_arg.a = x;
	execute_1_arg.b = y;
	execute_1_arg.path = path;

	result_1 = execute_1(&execute_1_arg, clnt);
	FILE *fptr = fopen(outputFile, "a");

	if (result_1->error)
	{
		printf("%s", result_1->errorString);
		fprintf(fptr, "FAIL:\n");
		fprintf(fptr,"%s", result_1->errorString);
	}
	else if (result_1 == (resultStruct *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		// *result = result_1->result; // Save the result returned by the server to result parameter given
		// printf("result: %d\n", *result);
		fprintf(fptr, "SUCCESS:\n");
		fprintf(fptr, "%d\n", result_1->result);
	}
	fclose(fptr);


#ifndef DEBUG
	clnt_destroy(clnt);
#endif
}

int main(int argc, char *argv[])
{
	if (argc < 4)

	{
		printf("usage: %s executable output_file server_host\n", argv[0]);
		exit(1);
	}

	// Read two integers from command line
	int n1, n2;
	scanf("%d %d", &n1, &n2);

	// Get command line arguments
	char *host = argv[3];
	char *outputfile = argv[2];
	// Create a variable to store the final result
	int result = 0;
	// make the call
	executer_1(host, n1, n2, argv[1], outputfile);

	// Open the given file in 'append' mode
	// FILE *fptr = fopen(outputfile, "a");
	// Append result to file
	// fprintf(fptr, "%d\n", result);
	// Close the file after writing
	// fclose(fptr);
	exit(0);
}
