/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "main.h"

bool_t
xdr_arguments (XDR *xdrs, arguments *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultStruct (XDR *xdrs, resultStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->error))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->errorString, ~0))
		 return FALSE;
	return TRUE;
}
