/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arguments {
	char *path;
	int a;
	int b;
};
typedef struct arguments arguments;

#define ADD_PROG 0x01010101
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define execute 1
extern  int * execute_1(arguments *, CLIENT *);
extern  int * execute_1_svc(arguments *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define execute 1
extern  int * execute_1();
extern  int * execute_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arguments (XDR *, arguments*);

#else /* K&R C */
extern bool_t xdr_arguments ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAIN_H_RPCGEN */
